### ISSUE TITLE
0.3 release

### ISSUE THREAD

**Issue by brylie** [conda-forge/fbprophet-feedstock#12]
Hei,
The fbprophet package recently released 0.3, which adds a nice multiplicative seasonality model mode. When/how will this package be updated for the fbprophet 0.3 release?

Regards,
Brylie

**Comment by rmax** [comment]
See my comment here https://github.com/conda-forge/fbprophet-feedstock/pull/11#issuecomment-397398152

**Comment by rmax** [comment]
Fixed by #11  🎉
